
# SEO settings
title: KVSHVL
description: "Programming of human behavior using architecture"
keywords: "architecture, people, places, film, Jekyll, theme, free, download, SEO, blog, web"
url: http://kvshvl.in
baseurl: "/simplest"
# baseurl: null

google_analytics: UA-105795582-1
repo: http://github.com/kvshvl/kvshvl.github.io

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Kushal Dhananjay Samant
  job      : Architect
  bio      : "Programming of human behaviour using architecture."
  thumb    : /images/author.jpg
  email    : kushaldsamant@gmail.com
  url      : http://kvshvl.in
  github   : http://github.com/kvshvl
  twitter  : http://twitter.com/kvshvl_
  facebook : http://facebook.com/kvshvl
  linkedin : http://linkedin.com/in/kvshvl

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@kvshvl_"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
