--- 
author: "Kushal Dhananjay Samant"
description: "Programming of human behavior using architecture."
email: kushaldsamant@gmail.com
google_analytics: UA-105795582-1
header_pages: 
  - "https://kvshvl.github.io/index.md"
  - "https://kvshvl.github.io/profile.md"
  - "https://kvshvl.github.io/practice.md"
  - "https://kvshvl.github.io/people.md"
  - "https://kvshvl.github.io/legal.md"
minima: 
  date_format: "%b %-d, %Y"
  social_links: 
    facebook: kvshvl
    github: kvshvl
    instagram: kvshvl
    linkedin: kvshvl
    rss: "https://anchor.fm/s/fe82330/podcast/rss"
    telegram: kvshvl
    twitter: kvshvl_
    youtube: jekyll
    youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    youtube_channel_name: CloudCannon
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
theme: minima
title: KVSHVL
